services:


  nocodb:
    image: "nocodb/nocodb:latest"
    environment:
      NC_DB: "pg://root_db:5432?u=postgres&p=password&d=root_db"
      NC_ADMIN_EMAIL: "mama@coco.com"
      NC_ADMIN_PASSWORD: "pipiloma!"
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - "nc_data:/usr/app/data"
    depends_on:
      root_db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080" ]
      interval: 10s
      timeout: 2s
      retries: 5


  root_db:
    ports:
      - "5432:5432"

    image: postgres
    environment:
      POSTGRES_DB: root_db
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres

    healthcheck:
      interval: 10s
      retries: 10
      test: "pg_isready -U \"$$POSTGRES_USER\" -d \"$$POSTGRES_DB\""
      timeout: 2s
    volumes:
      - "db_data:/var/lib/postgresql/data"
    restart: always

  bot:
    build: .
    container_name: secondbot
    environment:
      - API_TOKEN=${API_TOKEN}
      - NOCODB_BASE_URL=${NOCODB_BASE_URL}
      - NOCODB_API_TOKEN=${NOCODB_API_TOKEN}
      - ADMIN_IDS=${ADMIN_IDS}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - INVITE_URL=${INVITE_URL}
    volumes:
      - .:/app
    restart: always


volumes:
  db_data: {}
  nc_data: {}