version: "3.8"

services:
  bot:
    build: .
    container_name: secondbot
    environment:
      - API_TOKEN="7053839067:AAF6eUYIcKIXcNIdC0fGCnErFbsgwnOoS2c"
      - NOCODB_BASE_URL=http://host.docker.internal:8080
      - NOCODB_API_TOKEN="YcMwNErI54Q5_Dp5H07YTE6H0WDAv2Vsw_0YX35U"
    volumes:
      - .:/app
    restart: unless-stopped
    networks:
      - my_network

  nocodb:
    image: nocodb/nocodb:latest
    container_name: nocodb
    ports:
      - "8081:8080"
    environment:
      - NC_DB="pg://user:pass@postgres:5432/dbname"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge